# Generated by Django 2.2.16 on 2020-09-17 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_lead_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='datetime',
        ),
    ]
