# Generated by Django 2.2.16 on 2020-09-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_lead_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='click_on_video',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
