# Generated by Django 2.2.16 on 2020-09-17 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_lead_click_on_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='click_on_video',
        ),
    ]
